### ISSUE TITLE
Проверить ДЗ: Обои с функциями и доктестами

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW02_Wallpaper#4]
@coursar 
Добрый день!
Удалил все лишние проверки пользовательского ввода. 
Использовал функцию ceil из библиотеки math.

Создал отдельные репозитории для каждой домашней.
Venv создавал из терминала.

**Comment by coursar** [comment]
А requirements.txt?

**Comment by coursar** [comment]
Исправить #5, #6
